In [3]:
import numpy as np
np.__version__

'1.19.2'

## 배열 생성
### 리스트로 배열 만들기

In [21]:
# 1차원
a1= np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0],a1[1],a1[2],a1[3],a1[4])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5


In [138]:
# 2차원
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [23]:
# 3차원
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

In [25]:
# ones(): 모든요소를 1로 초기화
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# full(): 모든 요소를 지정한 값으로 초기화
np.full((3,3),2.54)

array([[2.54, 2.54, 2.54],
       [2.54, 2.54, 2.54],
       [2.54, 2.54, 2.54]])

In [29]:
# eye(): 단위행렬 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# tri(): 삼각행렬 생성
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [34]:
#empty(): 초기화되지 않은 배열 생성 그래서 빠름
np.empty(10)

array([-1.66157655e+036, -5.22037102e-053,  4.65187659e-308,
       -2.73699648e-048, -3.81152633e-032, -1.20950425e-009,
       -1.72229181e+036, -9.84906284e-058, -1.57234264e-063,
        0.00000000e+000])

In [41]:
#_like: 지정된 배열과 같은 shpae의 행렬 생성
print(a1)
print(np.zeros_like(a1))
print(a2)
print(np.ones_like(a2))
print(a3)
print(np.full_like(a3,10))

[1 2 3 4 5]
[0 0 0 0 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]


### 생성한 값으로 배열 생성

In [43]:
#arange: 정수 범위로 배열 생성
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
#linspace: 범위 내에서 균등 간격의 배열 생성
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
#logspace(): 범위 내에서 균등 간격으로 로그 스케일로 배열 생성
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성
* seed(): 난수 발생을 위한 시드 지정
* permutation(): 순서를 임의로 바꾸거나 임의의 순열 반환
* shuffle(): 리스트나 배열의 순서를 뒤섞음 
* binomial(): 이항분포에서 표본 추출
* beta(): 베타분포에서 표본 추출
* chisquare(): 카 서 표본 추출
* uniform(): 균등(0,1)분포에서 표본 추출

In [47]:
#random.random(): 랜덤한 수의 배열 생성
np.random.random((3,3))

array([[0.94410585, 0.56895274, 0.36806323],
       [0.59683566, 0.60497405, 0.74448084],
       [0.43426664, 0.98800274, 0.62777297]])

In [255]:
#random.randint(): 주어진 최소 최대 범위의 난수 추출
np.random.randint(0,10,(3,3)) 

array([[5, 2, 3],
       [6, 1, 4],
       [3, 1, 4]])

In [54]:
#random.normal(평균, 표준편차, 배열): 정규분포에서 표본 추출
np.random.normal(0,1,(3,3))

array([[ 1.43018797,  0.94971126,  0.65692046],
       [ 0.22203428,  0.59829059, -1.75037385],
       [ 0.13330585, -1.31520994, -0.9374954 ]])

In [55]:
#random.rand(): 균등분포에서 표본 추출
np.random.rand(3,3)

array([[0.58138896, 0.47918994, 0.38641911],
       [0.44046495, 0.40475733, 0.44225404],
       [0.03012328, 0.77600531, 0.55095838]])

In [58]:
#random.randn(): 표준정규분포를 고려한 랜덤한 수의 배열 생성
np.random.randn(3,3)

array([[ 0.68000189,  0.71660582,  0.47770485],
       [-0.66623993,  0.08448008, -0.33876049],
       [ 0.70592118, -1.6017614 ,  0.39324807]])

### 표준 데이터 타입
* bool: 바이트로 저장된 boolean
* int_: 기본 정수(integer) 타입
* uint_:부호 없는 정수
* float_: 실수
* complex: 복소수

In [66]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [68]:
np.full((3,3),2.54,dtype=float)

array([[2.54, 2.54, 2.54],
       [2.54, 2.54, 2.54],
       [2.54, 2.54, 2.54]])

### 날짜/시간 배열 생성
* Y:연
* M:월
* W:주
* D:일
* y:시
* m:분
* s:초
* ms:밀리초
* us:마이크로초
* ns:나노초

In [79]:
date = np.array('2020-01-01',dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [80]:
date+np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [81]:
datetime=np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [82]:
datetime=np.datetime64('2020-06-01 12:00:12.34','ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

## 배열 조회
### 배열 속성 정보
* strides: 다음으로 넘어가기 위한 바이트(큰단위,작은단위,작은단위,...)

In [88]:
def array_info(array):
    print(array)
    print("ndim: ", array.ndim)
    print("shape: ", array.shape)
    print("dtype: ", array.dtype)
    print("size: ", array.size)
    print("itemsize: ", array.itemsize)
    print("nbytes: ", array.nbytes)
    print("strides: ", array.strides)

In [89]:
array_info(a1)

[1 2 3 4 5]
ndim:  1
shape:  (5,)
dtype:  int32
size:  5
itemsize:  4
nbytes:  20
strides:  (4,)


In [90]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:  2
shape:  (3, 3)
dtype:  int32
size:  9
itemsize:  4
nbytes:  36
strides:  (12, 4)


In [91]:
  array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim:  3
shape:  (3, 3, 3)
dtype:  int32
size:  27
itemsize:  4
nbytes:  108
strides:  (36, 12, 4)


### 인덱싱(Indexing)

In [95]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[1 2 3 4 5]
1
3
5
4


In [96]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [97]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


In [95]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[1 2 3 4 5]
1
3
5
4


### 슬라이싱(Slicing)
* 슬라이싱 구문: a[start:stop:step]
* 기본값: start=0, stop=ndim, step=1

In [103]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1]
[1 3 5]
[5 4 3 2 1]


In [105]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2,:2])
print(a2[1:,::-1])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)
* 배열 각 요소의 선택 여부를 Boolean으로 지정
* True 값인 인덱스의 값만 조회

In [109]:
print(a1)
bi=[False,True,True,False,True]
print(a1[bi])

[1 2 3 4 5]
[2 3 5]


In [114]:
print(a2)
bi=np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False  True]
 [ True False  True]
 [False  True  True]]
[1 3 4 6 8 9]


### 팬시 인덱싱(Fancy Indexing)
* 인덱스 형식에 맞는 형식으로 값을 참조하여 출력함

In [118]:
print(a1)
print([a1[0],a1[2]])
ind = [0,2]
print(a1[ind])
ind=np.array([[0,1],[2,0]])
print(a1[ind])


[1 2 3 4 5]
[1, 3]
[1 3]
[[1 2]
 [3 1]]


In [121]:
print(a2)
row=np.array([0,2])
col=np.array([1,2])
print(a2[row,col]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


## 배열 값 삽입/수정/삭제/복사
### 배열값 삽입
* insert(): 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환
* axis는 행렬 표기를 기반으로 계산 하면 됨  
    -(5,3,2)모양의 행렬이 있다면 0은 5(행 간에) 1은 3(열 간에) 2는 2(깊이간)

In [124]:
print(a1)
b1 = np.insert(a1,0,10)
print(b1)
c1 = np.insert(a1,2,10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[ 1  2 10  3  4  5]


In [127]:
print(a2)
b2=np.insert(a2,1,10,axis=0)
print(b2)
c2=np.insert(a2,1,10,axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정
* 배열의 인덱싱으로 접근하여 값 수정

In [131]:
print(a1)
a1[0]=5
a1[1]=4
print(a1)
a1[:1]=9
print(a1)
i=np.array([1,3,4])
a1[i]=0
print(a1)
a1[i]+=4
print(a1)

[9 4 3 4 4]
[5 4 3 4 4]
[9 4 3 4 4]
[9 0 3 0 0]
[9 4 3 4 4]


In [145]:
print(a2)
a2[1,1]=2
a2[2,2]=3
print(a2)
a2[0]=1
print(a2)
a2[1:,2]=9
print(a2)
row=np.array([0,1])
col=np.array([1,2])
a2[row,col]= 0
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 3]]
[[1 1 1]
 [4 2 0]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제
* delete(): 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차열 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [147]:
print(a1)
b1=np.delete(a1,1)
print(b1)

[9 4 3 4 4]
[9 3 4 4]


In [150]:
print(a2)
b2=np.delete(a2,1,axis=0)
print(b2)
c2=np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사
* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님
* 원본 배열을 가져와서 조치를 취하는 것이기 때문에 바꾸면 원본이 달라짐

In [155]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1]=0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


* copy(): 배열이나 하위 배열 내의 값을 명시적을 복사

In [161]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1]=1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


## 배열 변환
### 배열 전치 및 축 변경

In [166]:
print(a2)
print(a2.T)
print(a3)
print(a3.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [169]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [171]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열의 재구조화
* reshape(): 배열의 형상을 변경

In [173]:
n1=np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* np.newaxis(): 새로운 축 추가

In [176]:
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])
#행으로 축을 추가하느냐 열로 축을 추가하느냐

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경
* resize((배열모양)): 배열 모양만 변경  
    - 배열의 크기 증가시 남은 공간은 0으로 채워짐  
    - 배열의 크기 감소도 가능한데 값이 있는 부분이 축소 될 경우 삭제됨


In [198]:
n2=np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[4 8 6 5 0]
 [0 5 1 3 2]]
[[4 8]
 [6 5]
 [0 0]
 [5 1]
 [3 2]]
[[4 8 6 5 0]
 [0 5 1 3 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [196]:
n2.resize((5,5))
print(n2)

[[2 5 1 1 0]
 [3 6 7 3 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [197]:
n2.resize((3,3))
print(n2)

[[2 5 1]
 [1 0 3]
 [6 7 3]]


### 배열추가
* append(): 배열의 끝에 값 추가
    * axis지정이 없으면 1차원 배열 형태로 변형되어 결합됨

In [201]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2=np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [202]:
c2=np.append(a2,b2,axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [204]:
c2=np.append(a2,b2,axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결
* concatenate():튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [206]:
a1= np.array([1,3,5])
b1= np.array([2,4,6])
np.concatenate([a1,b1]) 

array([1, 3, 5, 2, 4, 6])

In [209]:
a2=np.array([[1,2,3],
             [4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [210]:
a2=np.array([[1,2,3],
             [4,5,6]])
np.concatenate([a2,a2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* vstack(): 수직스택
* hstack(): 수평스택
* dstack(): 깊이스택
* stack(): 새로운 차원으로 연결

In [215]:
print(np.vstack([a2,a2]))
print(np.hstack([a2,a2]))
print(np.dstack([a2,a2]))
print(np.stack([a2,a2]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### 배열 분할
* split(분할할 배열, [자를인덱스]): 배열분할

In [226]:
a1=np.arange(0,10)
print(a1)
b1, c1 = np.split(a1,[5])
print(b1,c1)
b1, c1, d1,e1,f1=np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* vsplit(): 수직 분할, 1차원으로 분할

In [234]:
a2= np.arange(1,10).reshape(3,3)
print(a2)
b2,c2=np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* hsplit():수평분할,3차원으로 분할

In [232]:
a2= np.arange(1,10).reshape(3,3)
print(a2)
b2,c2=np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* dsplit():수직분할,3차원으로 분할

In [235]:
a3= np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3=np.hsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]

 [[19 20 21]
  [22 23 24]]]
[[[ 7  8  9]]

 [[16 17 18]]

 [[25 26 27]]]


## 배열 연산
    * Numpy의 배열연산은 백터화(vectorized)연산 사용
    * 일반적으로 NUmpy의 병용함수(universal function)를 통해 구현
    * 배열 요소에 대한 반복적인 계산을 효율적으로 수행
### 브로드캐스팅(Broadcasting)
    *계산할 경우 저차원이 고차원을 따라가서 계산을 하게 됨

In [239]:
a1=np.array([1,2,3])
print(a1)
print(a1+5)

a2=np.arange(1,10).reshape(3,3)
print(a2)
print(a1+a2)

b2=np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술연산
* np.add
* np.subtract
* np.negative
* np.multiply
* np.divide
* np.floor_divide:나눗셈 내림
* np.power: 지수 연산
* np.mod: 나머지 연산

In [251]:
a1=np.arange(1,10)
print(a1)
print(a1 +1)
print(np.add(a1,10))
print(a1 -1)
print(np.subtract(a1,10))
print(-a1)
print(np.negative(a1))
print(a1*2)
print(np.multiply(a1,2))
print(a1/2)
print(np.divide(a1,2))
print(a1//2)
print(np.floor_divide(a1,2))
print(a1**2)
print(np.power(a1,2))
print(a1%2)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [261]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2=np.random.randint(1,10,(3,3))
print(b2)
print(a2+b2)
print(a2*b2) #행렬 연산은 아님

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[8 8 5]
 [2 2 9]
 [8 9 9]]
[[ 9 10  8]
 [ 6  7 15]
 [15 17 18]]
[[ 8 16 15]
 [ 8 10 54]
 [56 72 81]]


#### 절대값 함수
* absolute(),abs(): 내장된 절대값 함수

In [266]:
a1= np.random.randint(-10,10,size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 5  9 -7 -5  0]
[5 9 7 5 0]
[5 9 7 5 0]


#### 제곱/제곱근 함수
* square, sqrt : 제곱, 제곱근 함수

In [268]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 5  9 -7 -5  0]
[25 81 49 25  0]
[2.23606798 3.                nan        nan 0.        ]


<ipython-input-268-4e034cb7ea92>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


#### 지수와 로그 함수(Exponential and Log)

In [273]:
a1=np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1)) # calculate 2**a1
print(np.power(a1,2))

[1 3 2 7 1]
[   2.71828183   20.08553692    7.3890561  1096.63315843    2.71828183]
[  2.   8.   4. 128.   2.]
[ 1  9  4 49  1]


In [275]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[1 3 2 7 1]
[0.         1.09861229 0.69314718 1.94591015 0.        ]
[0.         1.5849625  1.         2.80735492 0.        ]
[0.         0.47712125 0.30103    0.84509804 0.        ]


#### 삼각함수
* np.sin(array)
* np.arcsin(array)
* np.sinh(array)
* np.arcsinh(array) 
* np.deg2rad(array): 각도에서 라디안 변화
* np.rad2deg(array): 라디안에서 각도 변화
* np.hypol(array1,array2): 요소 별 유클리드 거리 계산

In [282]:
t=np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


### 집계함수 (nan이 써져 있는 경우 결측치 포함 계산)
* np.sum/ np.nansum
* np.cumsum / nan
* np.diff / nan: 차분=다른 값이 되기 위한 어떤 값
* np.prod / nan
* np.cumprod / nan
* np.dot: 점곱
* np.matmul: 행렬곱
* np.tensordot: 텐서곱
* np.cross: 벡터곱
* np.inner: 내적
* np.outer: 외적
* np.mean / nan
* np.std / nan
* np.var / nan
* np.min / nan
* np.max / nan
* np.argmin / nan: 최소값 인덱스
* np.argmax / nan: 최대값 인덱스
* np.median / nan
* np.percentile / nan:백분위 수 계산
* np.any: 요소 중 참이 있는지
* np.all: 모든 요소가 참인지

In [21]:
#sum()
a2=np.random.randint(1,10,(3,3))
print(a2)
print(a2.sum(),np.sum(a2))
print(a2.sum(axis=0),np.sum(a2,axis=0))
print(a2.sum(axis=1),np.sum(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
57 57
[17 23 17] [17 23 17]
[10 21 26] [10 21 26]


In [22]:
#cumsum()
print(a2)
print(a2.cumsum(),np.cumsum(a2))
print(np.cumsum(a2,axis=0))
print(np.cumsum(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
[ 1  8 10 18 25 31 39 48 57] [ 1  8 10 18 25 31 39 48 57]
[[ 1  7  2]
 [ 9 14  8]
 [17 23 17]]
[[ 1  8 10]
 [ 8 15 21]
 [ 8 17 26]]


In [23]:
#diff():
print(a2)
print(np.diff(a2))
print(np.diff(a2,axis=0))
print(np.diff(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
[[ 6 -5]
 [-1 -1]
 [ 1  0]]
[[7 0 4]
 [0 2 3]]
[[ 6 -5]
 [-1 -1]
 [ 1  0]]


In [24]:
#prod():
print(a2)
print(np.prod(a2))
print(np.prod(a2,axis=0))
print(np.prod(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
3048192
[ 64 441 108]
[ 14 336 648]


In [25]:
#cumprod():
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2,axis=0))
print(np.cumprod(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
[      1       7      14     112     784    4704   37632  338688 3048192]
[[  1   7   2]
 [  8  49  12]
 [ 64 441 108]]
[[  1   7  14]
 [  8  56 336]
 [  8  72 648]]


In [30]:
#cdot()/matmul():점곱/ 행렬곱 계산
print(a2)
b2=np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[10 10 10]
 [21 21 21]
 [26 26 26]]
[[10 10 10]
 [21 21 21]
 [26 26 26]]


In [33]:
#tensordot(): 텐서곱 계산
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
57
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[10 10 10]
 [21 21 21]
 [26 26 26]]


In [36]:
#cross(): 벡터곱(신발끈 공식??) 
x=[1,2,3]
y=[4,5,6]
print(np.cross(x,y))

[-3  6 -3]


In [39]:
#inner(),outer():
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[10 10 10]
 [21 21 21]
 [26 26 26]]
[[1 1 1 1 1 1 1 1 1]
 [7 7 7 7 7 7 7 7 7]
 [2 2 2 2 2 2 2 2 2]
 [8 8 8 8 8 8 8 8 8]
 [7 7 7 7 7 7 7 7 7]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [43]:
#mean(): 평균계산
print(a2)
print(np.mean(a2))
print(np.mean(a2,axis=0))
print(np.mean(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
6.333333333333333
[5.66666667 7.66666667 5.66666667]
[3.33333333 7.         8.66666667]


In [45]:
#std: 표준편차
print(a2)
print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
2.748737083745107
[3.29983165 0.94280904 2.86744176]
[2.62466929 0.81649658 0.47140452]


In [48]:
#var: 분산
print(a2)
print(np.var(a2))
print(np.var(a2,axis=0))
print(np.var(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
7.555555555555555
[10.88888889  0.88888889  8.22222222]
[6.88888889 0.66666667 0.22222222]


In [49]:
#min() / max(): 최소 최대값
#argmin() / argmax: 최소 최대 인덱스
print(a2)
print(np.argmax(a2))
print(np.argmax(a2,axis=0))
print(np.argmax(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
7
[1 2 2]
[1 0 1]


In [50]:
#median: 중앙값
print(a2)
print(np.median(a2))
print(np.median(a2,axis=0))
print(np.median(a2,axis=1))

[[1 7 2]
 [8 7 6]
 [8 9 9]]
7.0
[8. 7. 6.]
[2. 7. 9.]


In [55]:
#percentile: 백분위수 interpoation에 따라 달라짐
a1=np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolati on='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [59]:
#any(): 
a2=np.array([[False,False,False],
            [False,True,True],
            [False,True,True]])
print(a2)
print(np.any(a2))
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


In [62]:
#all():
print(a2)
print(np.all(a2))
print(np.all(a2,axis=0))
print(np.all(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
False
[False False False]
[False False False]


### 비교 연산(Comparison Operators)
* ==, !=, >=, <=, >, < 
* 기존 연산자에서 조건으로 추가하여 사용할 수 있음

In [69]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5))
print(np.sum(a2>5,axis=0))
print(np.sum(a2>5,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]


* 비교 범용함수
    * np.isclose(): 배열 두개가 일정수준으로 가까우면 True
    * np.isinf(): 배열이 inf이면 True
    * np.infinite(): 배열이 inf,nan이면 False
    * np.insnan(): 배열이 nan이면 True

In [71]:
a1=np.array([1,2,3,4,5])
print(a1)
b1=np.array([1,2,3,3,4])
print(b1)
print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [76]:
a1= np.array([np.nan,2,np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자
* &, |, ^(xor: 배타적 논리합= 교집합의 여집합), ~(not) 

### 배열 정렬
* np.sort(): 원본은 유지됨
* a1.sort(): 원본이 바뀜(a1은 해당 array)
* np.argsort(): 정렬한 것의 index

In [87]:
a1=np.random.randint(1,10,size=10)
print(a1)
print(np.sort(a1)) #원본은 유지됨
print(np.argsort(a1))

[5 7 6 2 7 6 2 3 6 5]
[2 2 3 5 5 6 6 6 7 7]
[3 6 7 0 9 2 5 8 1 4]


In [90]:
a2=np.random.randint(1,10,size=(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[5 2 8]
 [8 3 7]
 [3 5 4]]
[[3 2 4]
 [5 3 7]
 [8 5 8]]
[[2 5 8]
 [3 7 8]
 [3 4 5]]


#### 부분 정렬
* partition(): 배열에서 k개의 작은 값을 정렬

In [92]:
a1=np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3)) 

[4 3 8 2 2 3 6 5 5 8]
[2 2 3 3 4 8 6 5 5 8]


In [94]:
a2= np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))

[[9 4 8 5 6]
 [5 7 2 3 4]
 [9 1 4 6 3]
 [8 8 6 7 3]
 [8 8 2 8 2]]
[[8 1 2 3 3]
 [8 4 2 5 2]
 [5 7 4 6 3]
 [9 8 6 7 4]
 [9 8 8 8 6]]
[[5 6 4 8 9]
 [3 2 4 5 7]
 [1 3 4 6 9]
 [3 6 7 8 8]
 [2 2 8 8 8]]


## 배열 입출력
* np.save("파일이름",저장할객체): 객체 한개를 파일에 저장
* np.savez("파일이름",저장할객체, 저장할객체 ...): 객체 여려개를 한 파일에 저장
* np.load("파일이름.확장자"): 객체 로딩
* np.savetxt("파일이름.확장자",저장할객체, delimiter="구분자"):바이너리 타입이 아닌 텍스트 타입으로 저장, 대표적으로 csv(",")
* np.loadtxt(("파일이름.확장자",delimiter="구분자"): 텍스트 형태 로딩

In [95]:
a2=np.random.randint(1,10,size=(5,5))
print(a2)
np.save("a",a2)

[[4 9 6 3 2]
 [4 4 2 8 5]
 [4 7 6 3 9]
 [2 3 3 3 1]
 [9 3 5 1 6]]


In [97]:
b2=np.random.randint(1,10,size=(5,5))
print(b2)
np.savez("ab",a2,b2)

[[3 9 9 6 2]
 [6 8 9 9 3]
 [9 6 4 7 8]
 [1 4 1 4 6]
 [9 3 1 9 9]]


In [99]:
npy=np.load("a.npy")
print(npy)

[[4 9 6 3 2]
 [4 4 2 8 5]
 [4 7 6 3 9]
 [2 3 3 3 1]
 [9 3 5 1 6]]


In [101]:
npz=np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[4 9 6 3 2]
 [4 4 2 8 5]
 [4 7 6 3 9]
 [2 3 3 3 1]
 [9 3 5 1 6]]
[[3 9 9 6 2]
 [6 8 9 9 3]
 [9 6 4 7 8]
 [1 4 1 4 6]
 [9 3 1 9 9]]


In [102]:
print(a2)
np.savetxt("a.csv",a2,delimiter=",")

[[4 9 6 3 2]
 [4 4 2 8 5]
 [4 7 6 3 9]
 [2 3 3 3 1]
 [9 3 5 1 6]]


In [108]:
csv=np.loadtxt("a.csv",delimiter=",")
print(csv)

[[4. 9. 6. 3. 2.]
 [4. 4. 2. 8. 5.]
 [4. 7. 6. 3. 9.]
 [2. 3. 3. 3. 1.]
 [9. 3. 5. 1. 6.]]


In [109]:
print(b2)
np.savetxt("b.csv",b2,delimiter=",",fmt='%.2e',header="c1,c2,c3,c4,c5")

[[3 9 9 6 2]
 [6 8 9 9 3]
 [9 6 4 7 8]
 [1 4 1 4 6]
 [9 3 1 9 9]]


In [111]:
csv=np.loadtxt("b.csv",delimiter=",")
print(csv)

[[3. 9. 9. 6. 2.]
 [6. 8. 9. 9. 3.]
 [9. 6. 4. 7. 8.]
 [1. 4. 1. 4. 6.]
 [9. 3. 1. 9. 9.]]


 # 참고문헌
 * Numpy, https://numpy.org/
 * Jake Vanderplas, "Python Data Science Handbook",O'Reilly
 * Wes Mckinney,"Python for Data Analysis",O'Reilly
 * 이수안컴퓨터연구소(유튜버),https://www.youtube.com/watch?v=mirZPrWwvao&ab_channel=%EC%9D%B4%EC%88%98%EC%95%88%EC%BB%B4%ED%93%A8%ED%84%B0%EC%97%B0%EA%B5%AC%EC%86%8C
 * 깃허브 기록 누락 살리기