### 구글드라이브 연동



In [ ]:
# 구글드라이브 연동
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

# 구글 드라이브 파일 확인
!ls '/gdrive/My Drive/temp/'

# 반복되는 드라이브 경로 변수화
drive_path = '/gdrive/My Drive/temp/'

### 파이썬 머신러닝을 위한 모듈(라이브러리)


* 머신러닝 라이브러리
 * 사이킷런(Scikit-Learn)
* 행렬/선형대수/통계 라이브러리
  * **넘파이(NumPy): 고성능 과학계산을 위한 데이터 분석**(행렬, 선형대수)
  * 사이파이(SciPy): 자연과학, 통계
* 데이터 핸들링
 * 판다스(Pandas): 행과 열로 구성된 표 형식의 데이터(2차원 데이터 처리)
* 시각화
 * 맷플롯립(Matplotlib): 2D 그래프로 시각화
 * 시본(Seaborn): 다양한 색상 테마로 시각화

# Numpy (Numerical Python)
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 빠르고 효율적인 벡터 산술연산을 제공하는 n 차원 배열 (ndarray)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수 (sum(), sqrt(), mean())
- 선형대수, 난수 생성, 푸리에 변환

## Numpy 기초


In [ ]:
# Numpy 모듈(라이브러리)를 import하고 np 라는 이름으로 부르는 것이 관례
import numpy as np

numpy.ndarray

- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- N 차원 형태로 구성이 가능하다.
- 각 값들은 양의 정수로 색인(index)가 부여되어 있다.
- Numpy에서 차원(Dimension)을 rank, axis라고 부르기도 한다.
- ndarray를 줄여서 array로 표현한다.


In [ ]:
list=[1,2,3]
array1 = np.array(list)
print( type(array1) ) #타입은 함수니까 괄호안에 파라미터를 넣어주는것
print( array1.shape ) #배열의 크기확인

array2 = np.array( [ [1,2,3],
                    [4,5,6] ] ) #np 안에 들어있는 함수를 사용
print( type(array2) )
print( array2.shape ) # 객체= 속성!! 이니까 .속성나오는것 나오는것
array3 = np.array([[1,2,3]])
print( type(array3) )
print( array3.shape )

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


ndarray.shape

해당 array의 크기를 알 수 있다.

- ndarray의 차원과 크기를 튜플(tuple) 형태로 출력

- shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

- 위에서 array1.shape의 결과는 (3,) 으로써, 1차원의 데이터이며 총 3라는 크기를 갖고 있음을 알 수 있다.

- array2.shape의 결과는 (2,3) 으로써, 2차원의 데이터이며 2 * 3 크기를 갖고 있는 array 이다.


In [ ]:
# array 차원(Dimension) 확인
array1.ndim, array2.ndim, array3.ndim

(1, 2, 2)

In [ ]:
# array의 전체 요소 개수 확인
array1.size, array2.size, array3.size


(3, 6, 3)

numpy에서 사용되는 자료형

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_


In [ ]:
# ndarray내의 데이터 타입 확인
list1=[1,2,3]
print(type(list1))

array1= np.array(list)
print(type(array1))
print(array1)
print(array1.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]
int64


In [ ]:
# 서로 다른 데이터 타입을 갖을 때
list2=[1,2,'test']
array2 = np.array(list2)
print( array2, array2.dtype )

list3= [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64



- 리스트와 다르게 ndarray는 같은 데이터 타입만 가능.
- 서로 다른 데이터 타입이 섞여 있을 경우 큰 데이터 타입으로 형 변환을 일괄 적용

In [ ]:
# 데이터 타입 변경하기
array_int = np.array([1,2,3])
print(array_int, array_int.dtype)

array_float=array_int.astype(float)
print(array_float, array_float.dtype)

array_int32 = array_int.astype('int32')
print(array_int32, array_int32.dtype)

array_float2=np.array([1.2,2.1,3.1])
array_int2 = array_float2.astype('int32')
print(array_float2, array_float2.dtype)
print(array_int2, array_int2.dtype)


[1 2 3] int64
[1. 2. 3.] float64
[1 2 3] int32
[1.2 2.1 3.1] float64
[1 2 3] int32


In [ ]:
# 타입 지정하여 생성
array_int = np.array( [1.1,2.1,3.1] , dtype=np.int64 )
print( array_int, array_int.dtype)

[1 2 3] int64


#### Numpy 예제 01
Numpy를 이용해 다음과 같은 3차원 배열을 만들고 배열의 크기, 차원, 전체 요소 개수을 확인해보자 
```
array([[[1,2],
        [3,4]],
        
       [[5,6],
        [7,8]]])
```
```
배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8
```


In [ ]:
arr = np.array( [ [ [1,2],[3,4] ], [ [5,6],[7,8] ] ] )
print('배열의 크기: ',arr.shape)
print('배열의 차원: ',arr.ndim)
print('배열의 개수: ',arr.size)


배열의 크기:  (2, 2, 2)
배열의 차원:  3
배열의 개수:  8


### ndarray 생성

In [ ]:
# 연속값으로 생성
seq_array = np.arange(10)
seq_array, seq_array.dtype, seq_array.shape 

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'), (10,))

In [ ]:
# 초기화
zero_array = np.zeros( (3,2) ,dtype = 'int32')
print( zero_array )
print( zero_array.shape )

one_array = np.ones( (3,2) )
print(one_array, one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


In [ ]:
# 특정한 값으로 초기화
full_array = np.full((5,5),'na')
full_array

array([['na', 'na', 'na', 'na', 'na'],
       ['na', 'na', 'na', 'na', 'na'],
       ['na', 'na', 'na', 'na', 'na'],
       ['na', 'na', 'na', 'na', 'na'],
       ['na', 'na', 'na', 'na', 'na']], dtype='<U2')

In [ ]:
# 랜덤 값으로 초기화
np.random.rand(2,3)

array([[0.92872645, 0.67814104, 0.58710904]])

In [ ]:
# 랜덤 값 범위지정
np.random.randint(2,10, size = (2,3))

array([[5, 3, 8],
       [6, 4, 6]])

#### Numpy 예제 02
1,2,3,....,50 이 담긴 배열을 생성하시오.

In [ ]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### ndarray 차원과 크기 변경

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 자동변환 할 때는 -1을 넣어주면 됨, 자동으로 호환됨
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print(array2)

array3 = array1.reshape(-1,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# ndarray 형태를 통일
# 원본 ndarray가 어떤 형태라도 2차원이고 1개의 컬럼을 갖는 ndarray로 변환
array1 = np.arange(8)
array3d = array1.reshape( (2,2,2) )
print( array3d.tolist() )

array5 = array3d.reshape(-1,1)
print(array5.tolist(), array5.shape)

array6= array1.reshape(-1,1)
print(array6.tolist(),array6.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


### ndarray 인덱싱 & 슬라이싱
- 특정 데이터 추출
- 슬라이싱(Slicing) : 연속된 데이터 추출
- 팬시 인덱싱(Fancy Indexing) : 리스트 또는 ndarray 형태의 인덱싱 집합을 이용하여 여러 데이터를 추출
- 불린 인덱싱(Boolean Indexing) : True/False 값 인덱싱 집합을 이용하여 해당 인덱스 위치에 있는 데이터를 추출

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array = np.arange(start = 1, stop= 10)
print(array)

v = array[2]
print('value: ', v)
print(type(v))

[1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [ ]:
# 인덱스를 이용한 데이터 수정
array[0] = 9 
array[8] = 0
array

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [ ]:
array = np.array( [[1,2,3],
                   [4,5,6]] )

print(array[0])
print(array[0][0])
print(array[0,0])

[1 2 3]
1
1


In [ ]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

print(array2d)
print("row = 0, col = 0", array2d[0,0])
print("row = 0, col = 1", array2d[0,1])
print("row = 0, col = 0", array2d[0,2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
row = 0, col = 0 1
row = 0, col = 1 2
row = 0, col = 0 3


슬라이싱
- ':' 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 맨 처음/마지막 인덱스로 간주



In [ ]:
# 1차원 슬라이싱
arr = np.arange(1,10)
arr[0:3], arr[:3], arr[3:], arr[:]

(array([1, 2, 3]),
 array([1, 2, 3]),
 array([4, 5, 6, 7, 8, 9]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# 2차원 슬라이싱
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
array[1:3,0:3]


array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[1:3,1:-1]

array([[4, 5],
       [7, 8]])

In [ ]:
array[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
array[1:,:2]

array([[4, 5],
       [7, 8]])

In [ ]:
# 팬시 인덱싱 1차원


In [ ]:
# 팬시 인덱싱 2차원


In [ ]:
# 불린 인덱싱
# 조건 필터링과 검색이 동시 가능


In [ ]:
# ndarray에 조건식 할당


In [ ]:
# 불린 인덱싱 응용


#### Numpy 예제 03 

BMI 구하기

10명에 대한 키와 몸무게가 들어있는 파일 ‘height_weight.txt’을 읽어 각 사람별 BMI 지수를 구하시오.
```
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data
```
  \\( BMI지수=\frac { 몸무게(kg) }{ 키(m) \times 키(m) } \\)
```
# 제곱 계산
# **2 or np.square()
```

In [ ]:
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [ ]:
# BMI 구하기


### 행렬의 정렬
- sort() : 정렬
- argsort() : 정렬된 행렬의 원본 행렬 원소에 대한 인덱스를 반환

In [ ]:
# 내림차순으로 정렬


In [ ]:
# 정렬된 행렬의 인덱스 반환


In [ ]:
# argsort() 활용 - 팬시 인덱스로 적용


### ndarray 연산
- 일반연산 : 산술연산, 비교연산 ...
- 선형대수 연산 : 행렬 내적과 전치 행렬

In [ ]:
# 행렬 내적(행렬 곱)


In [ ]:
# 전치행렬 : 행과 열의 위치를 교환한 행렬


### Universal 함수
- sin(), cos()다양한 수학함수를 제공
- 스칼라값을 입력으로 하는 math 패키지와 달리 배열에 대해 요소별로 적용

#### Numpy 예제 04

영화평점 데이터 분석

In [ ]:
import numpy as np

# 사용자 아이디, 영화 아이디, 평점, ?
data = np.loadtxt(drive_path + "ratings_small.txt", delimiter = "::", dtype = np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     1779,      2502,         4, 998699749],
       [     1779,      3160,         5, 977032398],
       [     1779,      3168,         4, 977033232]])

##### 데이터 분석하기
```
print(data.ndim)
print(data.shape)
print(data.size)
```

In [ ]:
# 행(평점 작성개수) 1200004개 열(데이터의 종류) 4개
# 1200004 * 4 = 4800016


##### 전체 평점 평균 구하기
1. 평점 데이터만 추출 (인덱싱, 슬라이싱)
2. 평균 구하기 (mean)

In [ ]:
# 전체 평점 평균 평점


##### 각 사용자별 평점 평균 구하기
1번 사용자의 평균 평점 구하기
1. 1번 사용자의 데이터만 Boolean Indexing 추출
2. 1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
3. 평균 구하기

참고
```
# 중복된 성분을 제외한 array를 반환
np.unique( ndarray )
```

In [ ]:
# 1번 사용자 평점 평균


In [ ]:
# 각 사용자별 평점 평균


##### 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
- 리스트는 Boolean Indexing이 안되니 배열로 변환해야 인덱싱, 슬라이싱 가능

In [ ]:
# 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기


##### CSV 파일로 저장
- np.savetxt() 이용

In [ ]:
# csv 저장


## Numpy 요약

In [ ]:
import numpy as np

In [ ]:
# 2차원 리스트로부터 2차원 배열을 만드는 예


In [ ]:
# list를 ndarray로


In [ ]:
# 배열의 각 항목의 타입을 알아보려면 dtype 속성값을 보면 된다


In [ ]:
# 배열의 구조를 보려면 shape 속성을 보면 된다


In [ ]:
# 초기값이 0인 배열을 만드는 법


In [ ]:
# 레인지(범위)를 만드는 법


In [ ]:
# 레인지 형태로 배열을 만드는 법


In [ ]:
# 데이터의 타입을 변경하려면 astype을 사용한다


In [ ]:
# 벡터화: 배열에 상수를 곱하거나 더할 수 있다


In [ ]:
# 배열을 곱하면 각 항목별로 곱셈을 한다


In [ ]:
# 전체는 ':'로 표시할 수 있다


In [ ]:
# 0~11 값을 얻고 이를 4x3 배열로 재구성한다


In [ ]:
# 5 보다 큰 값을 모두 5로 교체하는 방법


In [ ]:
# 행의 순서를 임의의 순으로 바꿀 수 있다
# 팬시 색인으로 배열을 바꾸면 본사본이 생기며 원래의 내용을 바지 않는다


In [ ]:
# data 내용은 그대로 남아 있다

In [ ]:
# 행과 열을 모두 바꾸려면 아래와 같이 한다


In [ ]:
# 트랜스포즈는 행과 열의 위치를 바꾸는 것이다


In [ ]:
# 배열의 곱셈은 np.dot()을 사용한다


In [ ]:
# 각 행에 대해서 평균을 구한다 axis=1이면 행을 지칭한다


In [ ]:
# axis를 생략해도 된다


In [ ]:
# 각 열에 대해서 평균을 구한다 axis=0이면 열을 지칭한다


In [ ]:
# 불리언 연산, True는 1로 False는 0으로 숫자로 치환하여 계산가능하다


In [ ]:
# 배열에서 값이 특정 수보다 큰 원소의 갯수를 반환한다.


In [ ]:
# 열을 기준으로 소팅


In [ ]:
# 행에서 소팅


In [ ]:
# 순서를 임의로 바꾸는 방법
